name: rewear
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ms_material_color: ^1.0.0
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  get_storage: ^2.0.3
  rxdart: ^0.27.4
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  record: ^4.3.1
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.9
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.4.0 # https://github.com/firebase/flutterfire/issues/2751

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/png/shirts/
    - assets/fonts/
    - assets/fonts/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/black.ttf
        - asset: assets/fonts/roboto/blackItalic.ttf
        - asset: assets/fonts/roboto/bold.ttf
        - asset: assets/fonts/roboto/boldItalic.ttf
        - asset: assets/fonts/roboto/italic.ttf
        - asset: assets/fonts/roboto/light.ttf
        - asset: assets/fonts/roboto/lightItalic.ttf
        - asset: assets/fonts/roboto/medium.ttf
        - asset: assets/fonts/roboto/mediumItalic.ttf
        - asset: assets/fonts/roboto/regular.ttf
        - asset: assets/fonts/roboto/thin.ttf
        - asset: assets/fonts/roboto/thinItalic.ttf
    - family: IconlyFont
      fonts:
        - asset: assets/fonts/icons/IconlyFont.ttf
